screen: tuple[str] = (
    'BBBBBBBBBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBBBBBBBBBB',
    'BB                   BB',
    'BB                   BB',
    'BB                   BB',
    'BB                   BB',
    'BB                   BB',
    'BB                   BB',
    'BB                   BB',
    'BB                   BB',
    'BBBBBBBBBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBBBBBBBBBB',
)
room: tuple[str] = (
    'BBBBBBBBBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBBBBBBBBBB',
    'BB                   BB',
    'BB                   BB',
    'BB                   BB',
    'BB   BB     BBBBBBBBBBB',
    'BB             BBBBBBBB',
    'BB       B       BBBBBB',
    'BB      BB BB      BBBB',
    'BB     BBB BBBB     BBB',
    'BBBBBBBBBBBBBBBB    BBB',
    'BBBBBBBBBBBBBBBBBBBBBBB',
)
hundred: tuple[str] = (
    'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                                                                                                BB',
    'BB                         BB   BB                                                                BB',
    'BB                                                                                                BB',
    'BB                      BB                                                                        BB',
    'BB                     BBB         BB   B   B   B   B   B   B   B   B  B   B   B   B   B   B   BBBBB',
    'BB                   BBBBB                                                                        BB',
    'BB                              BB                                                                BB',
    'BB                                                                                                BB',
    'BB                          BBB                                                                   BB',
    'BB                                                                                                BB',
    'BB                  BB   BB                                                                       BB',
    'BB                                                                                                BB',
    'BB               BB                                                                               BB',
    'BB                                                                                                BB',
    'BB            B                                                                                   BB',
    'BB           BB                                                                                   BB',
    'BB          BBB                                                                                   BB',
    'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
)
